/*
 * BackendRegistry.h
 *
 * Registry of output backends keyed by their target-language string.
 *
 * The output language is selected by string (see Xsc::TargetLanguage in
 * <Xsc/Targets.h>) so the compiler core never has to name any backend. Each backend
 * folder provides a RegisterBackend_* function; CMake assembles the set present in
 * this build into RegisterBackends() (declared below), which the registry invokes
 * once, lazily, on first access. The compiler dispatches by looking the requested
 * target language up here and invoking the registered factory.
 *
 * This file is part of the XShaderCompiler project (Copyright (c) 2014-2017 by Lukas Hermanns)
 * See "LICENSE.txt" for license information.
 */

#ifndef XSC_BACKEND_REGISTRY_H
#define XSC_BACKEND_REGISTRY_H


#include "OutputShaderVersion.h"
#include <Xsc/Export.h>
#include <functional>
#include <map>
#include <memory>
#include <string>
#include <vector>


namespace Xsc
{


class Generator;
class Log;
struct ShaderOutput;


// Describes one registered output backend (one target-language identifier).
struct BackendDescriptor
{
    // Creates a fresh generator instance for this backend.
    using Factory = std::function<std::unique_ptr<Generator>(Log*)>;

    // Internal numeric version handed to the GLSL/HLSL emitters. Backends that do
    // not reason about a numeric version may use any reasonable value.
    OutputShaderVersion version;

    // Generator factory. Must not be null for a usable backend.
    Factory             factory;

    // Macros the host predefines on the preprocessor before parsing, when this
    // backend is selected as the output target. Lets each backend declare its
    // own user-facing sentinel (e.g. an XSC_<target> guard for `#ifdef` regions
    // that don't translate to this backend) without the core needing to know
    // the backend's identifier. Empty for backends that need no sentinel.
    std::map<std::string, int> predefinedMacros;
};


// Global registry of output backends, keyed by target-language string.
class XSC_EXPORT BackendRegistry
{

    public:

        // Returns the singleton instance. The registry is populated lazily on the
        // first read (see Find / SupportedLanguages), not at construction.
        static BackendRegistry& Instance();

        // Registers (or replaces) the backend for the specified target language.
        void Register(const std::string& targetLanguage, const BackendDescriptor& desc);

        // Returns the descriptor for the specified target language, or null if none is registered.
        const BackendDescriptor* Find(const std::string& targetLanguage) const;

        // Returns all registered target-language identifiers.
        std::vector<std::string> SupportedLanguages() const;

        // Ensures every backend baked into this build (via the CMake-generated RegisterBackends)
        // has registered itself. Idempotent -- the generated registrars run at most once. Invoked
        // automatically on the read paths, and by LoadBackend before a runtime-loaded backend
        // registers, so a loaded backend deterministically overrides a baked-in one of the same
        // target language regardless of read order.
        void EnsureBuiltinsRegistered() const;

    private:

        BackendRegistry() = default;

        std::map<std::string, BackendDescriptor> backends_;

};


// Registers every output backend compiled into this build. The implementation is
// generated by CMake (BackendRegistrations.generated.cpp) from the backend folders
// present, so it may be empty; the generic name keeps the core from naming any
// individual backend. Called once, lazily, before the registry is first read.
//
// A backend's RegisterBackend_<Name>() free function is the single registration leaf,
// reached through one of two triggers: it is either called from this generated
// RegisterBackends() (a backend baked into the core), or from a separately-loaded
// backend DLL's XscRegisterBackend entry point (see Xsc::LoadBackend in <Xsc/Backend.h>).
void RegisterBackends();


// Resolves the internal numeric output version for the given output descriptor's
// target language. Returns OutputShaderVersion::GLSL if the language is unknown.
OutputShaderVersion ResolveOutputShaderVersion(const ShaderOutput& outputDesc);


} // /namespace Xsc


#endif



// ================================================================================
