/*
 * BackendRegistry.cpp
 *
 * This file is part of the XShaderCompiler project (Copyright (c) 2014-2017 by Lukas Hermanns)
 * See "LICENSE.txt" for license information.
 */

#include "BackendRegistry.h"
#include <Xsc/Targets.h>
#include <Xsc/Xsc.h>


namespace Xsc
{


BackendRegistry& BackendRegistry::Instance()
{
    static BackendRegistry instance;
    return instance;
}

namespace
{

/*
Ensures every backend compiled into this build has registered itself, exactly once.
RegisterBackends() is generated by CMake from the set of backend folders present (it
may be empty); each RegisterBackend_* it calls populates the registry through
BackendRegistry::Register. This is triggered from the registry's read paths (Find /
SupportedLanguages) and never from Register itself, so the backend registrars cannot
re-enter this one-time guard.
*/
void EnsureBackendsRegistered()
{
    static const bool registered = []
    {
        RegisterBackends();
        return true;
    }();
    (void)registered;
}

} // /anonymous namespace

void BackendRegistry::Register(const std::string& targetLanguage, const BackendDescriptor& desc)
{
    backends_[targetLanguage] = desc;
}

const BackendDescriptor* BackendRegistry::Find(const std::string& targetLanguage) const
{
    EnsureBackendsRegistered();
    auto it = backends_.find(targetLanguage);
    return (it != backends_.end() ? &(it->second) : nullptr);
}

std::vector<std::string> BackendRegistry::SupportedLanguages() const
{
    EnsureBackendsRegistered();
    std::vector<std::string> result;
    result.reserve(backends_.size());
    for (const auto& entry : backends_)
        result.push_back(entry.first);
    return result;
}

OutputShaderVersion ResolveOutputShaderVersion(const ShaderOutput& outputDesc)
{
    if (const auto* desc = BackendRegistry::Instance().Find(outputDesc.targetLanguage))
        return desc->version;
    return OutputShaderVersion::GLSL;
}

XSC_EXPORT std::vector<std::string> GetSupportedTargetLanguages()
{
    return BackendRegistry::Instance().SupportedLanguages();
}

XSC_EXPORT bool IsTargetLanguageSupported(const std::string& targetLanguage)
{
    return (BackendRegistry::Instance().Find(targetLanguage) != nullptr);
}


} // /namespace Xsc



// ================================================================================
